### ISSUE TITLE
求问项目中的杭州OD矩阵

### ISSUE THREAD

**Issue by haaanlin** [zjuyfy/zjuMCM#1]
大佬可以分享一下求解中用到的“OD矩阵表.txt”“杭州xy.txt”等文件吗

**Comment by zjuyfy** [comment]
数据是用arcgis等软件导出来的，文件有点大，你留个邮箱吧。

**Comment by haaanlin** [comment]
> 数据是用arcgis等软件导出来的，文件有点大，你留个邮箱吧。

万分感谢！我的邮箱是281355538@qq.com

**Comment by zjuyfy** [comment]
已发送
